### PR TITLE
Rework of your plugin

### PR DESCRIPTION
**Pull request by LuckyMutt**
Hey there!

Here is a complete rework of your plugin. Because it actually almost replaces everything from your original plugin I set myself as owner in the plugin. Still, I won't publish it.

The approach I took with your plugin was using your idea but instead of creating static items, I decided that the user should be able to create the items (rings) themselves dynamically. You can check out my codebase if you want to.

If you decide to use my version, which is totally fine, and you sure can expand it, please be sure to credit me.

Hope this helps you for your project and maybe future projects.

### CODE REVIEW

**Comment by Fotohh** [comment]
Firstly, conflicts must be resolved, secondly, you repeat the same chunks of code repeatedly leading to some classes going up to around 300 lines of code. Try to compress that down, by making methods that take in the data. if you don't know what I mean view the main file.

**Comment by LuckyMutt** [comment]
Resolving conflicts is on your side. Can't manage that.
Also, there are some repetitions in the RingManager which could be abstracted. I will change that later on.

Btw. you should also check your code about repeating code. There's also a lot there (Just one part would be the onClick.java file where every if case has to check if it has the same permission all over again. Maybe a switch statement would also help in a lot of cases. Also, you shouldn't suppress deprecated warnings. They are there for a reason. 

Another thing would be the check for your rings. It is by no way a save check to be sure it is an actual ring. I mean, you should check more than just a material and if the item hast some itemeta. When I tested my version, I had to disable the original because it trigged the ring without it actually being a ring.

**Comment by Fotohh** [comment]
> Resolving conflicts is on your side. Can't manage that. Also, there are some repetitions in the RingManager which could be abstracted. I will change that later on.
> 
> Btw. you should also check your code about repeating code. There's also a lot there (Just one part would be the onClick.java file where every if case has to check if it has the same permission all over again. Maybe a switch statement would also help in a lot of cases. Also, you shouldn't suppress deprecated warnings. They are there for a reason.
> 
> Another thing would be the check for your rings. It is by no way a save check to be sure it is an actual ring. I mean, you should check more than just a material and if the item hast some itemeta. When I tested my version, I had to disable the original because it trigged the ring without it actually being a ring.

I just cleaned up their code nothing more, I didn't touch it at all except for extracting it into different classes. The code listed here isn't my actual code, it's still theirs, just slapped into different classes. I didn't go as far as spoon-feeding a whole plugin. Mb for not giving enough context xD

**Comment by LuckyMutt** [comment]
Well under cleanup, I would also understand fixing grave mistakes. If that's what you did, it's just a reshift. So far, I would say for sure you changed code in an attempt to optimize it. But there is definitely a lot of way for improvement.

It's actually not my intention to discuss with you here. @lilsimmi asked for help, I read his wanted stuff, looked at his codebase and choose to use a different approach. You might call it spoon-feeding with the obvious intention to make it sound negative. But he/she'll have enough work with getting around the actual code, understanding it. Having the possibilities to pick up new practices to improve his current or future projects.

**Comment by Fotohh** [comment]
Yes, most definitely, I think having code to compare and contrast with his current code will definitely help improve his coding capabilities.

**Comment by Fotohh** [comment]
@lilsimmi merge please. and also try to read through the code in a attempt to understand which each line does, it'll help you a lot.

**Review by lilsimmi — APPROVED** [review]

**Comment by lilsimmi** [comment]
approved!

**Pull request merged**
